// packages/likec4/app/react/components/LikeC4Browser.tsx
import { LikeC4Diagram } from '@likec4/diagram'
import { ActionIcon } from '@mantine/core'
import { useMountEffect } from '@react-hookz/web'
import { IconX } from '@tabler/icons-react'
import { useId, useRef, useState } from 'react'
import { closeButton, cssDiagram } from './LikeC4Browser.css'
import { ShadowRoot } from './ShadowRoot'
import { ShadowRootMantineProvider } from './ShadowRootMantineProvider'
import { useColorScheme } from './styles'
import * as css from './styles.css'
import type { DiagramView, LikeC4ViewBaseProps } from './types'

export type LikeC4BrowserProps<ViewId extends string> = Omit<LikeC4ViewBaseProps<ViewId>, 'viewId' | 'interactive'> & {
  view: DiagramView<ViewId>
  onNavigateTo: (to: ViewId) => void
  onClose: () => void
}

export function LikeC4Browser<ViewId extends string>({
  colorScheme,
  view,
  injectFontCss,
  onNavigateTo,
  onClose,
  background = 'dots'
}: LikeC4BrowserProps<ViewId>) {
  const [opened, setOpened] = useState(false)
  const dialogRef = useRef<HTMLDialogElement>(null)
  const id = useId()
  const scheme = useColorScheme(colorScheme)

  useMountEffect(() => {
    dialogRef.current?.showModal()
    setTimeout(() => {
      setOpened(true)
    }, 20)
  })
  const closeMe = () => {
    setTimeout(() => {
      onClose()
    }, 400)
  }

  const backdropRgb = scheme === 'dark' ? '36 36 36' : '255 255 255'

  return (
    <>
      <style
        type="text/css"
        dangerouslySetInnerHTML={{
          __html: `
        @keyframes likec4-dialog-fade-in {
          0% {
            opacity: 0;
            transform: scale(0.7);
            display: none;
          }

          100% {
            opacity: 1;
            transform: scale(1);
            display: block;
          }
        }

        @keyframes likec4-dialog-fade-out {
          0% {
            opacity: 1;
            transform: scale(1);
            display: block;
          }

          100% {
            opacity: 0;
            transform: scale(0.85);
            display: none;
          }
        }

        @keyframes likec4-dialog-backdrop-fade-in {
          0% {
            background-color: rgb(${backdropRgb} / 5%);
          }

          100% {
            background-color: rgb(${backdropRgb} / 90%);
          }
        }
        [data-likec4-instance="${id}"] {
          top: 0;
          left: 0;
          padding: 0;
          margin: 0;
          border: 0 solid transparent;
          box-sizing: border-box;
          width: 100%;
          min-width: 100dvw;
          height: 100%;
          min-height: 100dvh;
          background: transparent;
          animation: likec4-dialog-fade-out 0.15s ease-out;
          transform-origin: 50% 20%;
        }
        [data-likec4-instance="${id}"][open] {
          animation: likec4-dialog-fade-in 0.3s ease-out;
        }
        [data-likec4-instance="${id}"] > div {
          width: 100%;
          height: 100%;
          padding: 0;
          margin: 0;
          border: 0 solid transparent;
          box-sizing: border-box;
        }
        [data-likec4-instance="${id}"]::backdrop {
          -webkit-backdrop-filter: blur(8px);
          backdrop-filter: blur(8px);
          background-color: rgb(${backdropRgb} / 5%);
        }
        [data-likec4-instance="${id}"][open]::backdrop {
          animation: likec4-dialog-backdrop-fade-in 500ms ease-out forwards;
        }
      `
        }} />
      <dialog
        aria-modal="true"
        data-likec4-instance={id}
        ref={dialogRef}
        onClose={closeMe}>
        <ShadowRoot injectFontCss={injectFontCss}>
          <ShadowRootMantineProvider
            colorScheme={scheme}
            className={css.cssLikeC4Browser}
          >
            {opened && (
              <LikeC4Diagram
                className={cssDiagram}
                view={view as any}
                readonly
                pannable
                zoomable
                fitView
                fitViewPadding={0.05}
                showDiagramTitle
                showElementLinks
                enableDynamicViewWalkthrough
                showNavigationButtons
                background={background}
                controls={false}
                nodesSelectable={false}
                nodesDraggable={false}
                keepAspectRatio={false}
                onNavigateTo={to => onNavigateTo(to as string as ViewId)}
              />
            )}
            <ActionIcon
              className={closeButton}
              variant="light"
              color="gray"
              autoFocus
              onClick={() => dialogRef.current?.close()}>
              <IconX />
            </ActionIcon>
          </ShadowRootMantineProvider>
        </ShadowRoot>
      </dialog>
    </>
  )
}

// packages/likec4/app/webcomponent/LikeC4Browser.tsx
import { invariant } from '@likec4/core'
import { LikeC4Diagram } from '@likec4/diagram'
import { MantineProvider, ModalBody, ModalCloseButton, ModalContent, ModalRoot } from '@mantine/core'
import { useTimeoutEffect } from '@react-hookz/web'
import { memo, useEffect, useState } from 'react'
import { createRoot, type Root } from 'react-dom/client'
import { type DiagramView, type LikeC4ViewId, LikeC4Views } from 'virtual:likec4/views'
import { RenderIcon } from './RenderIcon'
import { bundledStyles, matchesColorScheme, theme } from './styles'

const BrowserModal = memo<{
  view: DiagramView
  onNavigateTo: (to: string) => void
  onClose: () => void
}>((
  {
    view,
    onNavigateTo,
    onClose
  }
) => {
  const [opened, setOpened] = useState(false)
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    setOpened(true)
  }, [])

  useTimeoutEffect(() => {
    setVisible(true)
  }, 20)

  return (
    (
      <ModalRoot
        keepMounted
        opened={opened}
        lockScroll={false}
        fullScreen
        trapFocus={false}
        withinPortal={false}
        onClose={() => {
          setOpened(false)
          setTimeout(onClose, 200)
        }}>
        <ModalContent>
          <ModalCloseButton />
          <ModalBody w={'100%'} h={'100%'} p={0}>
            {visible && (
              <LikeC4Diagram
                view={view as any}
                readonly
                pannable
                zoomable
                fitView
                fitViewPadding={0.08}
                showDiagramTitle
                showElementLinks
                enableDynamicViewWalkthrough
                showNavigationButtons
                controls={false}
                nodesSelectable={false}
                nodesDraggable={false}
                keepAspectRatio={false}
                renderIcon={RenderIcon}
                onNavigateTo={onNavigateTo} />
            )}
          </ModalBody>
        </ModalContent>
      </ModalRoot>
    )
  )
}, (prev, next) => prev.view === next.view)

export class LikeC4Browser extends HTMLElement {
  static observedAttributes = ['view-id']

  private shadowRootEl: HTMLDivElement
  private shadow: ShadowRoot
  private root: Root | undefined

  private bundledCSS: CSSStyleSheet | undefined
  private hostCss: CSSStyleSheet | undefined

  private lastHostCss = ''

  constructor() {
    super()
    this.shadow = this.attachShadow({ mode: 'open' })
    this.shadow.innerHTML = '<div class="likec4-shadow-root likec4-browser"><div class="likec4-react-root"></div></div>'
    this.shadowRootEl = this.shadow.querySelector('.likec4-shadow-root') as HTMLDivElement
  }

  updateHostCss() {
    const hostCss = `
    :host {
      position: fixed;
      top: 0;
      left: 0;
      padding: 0;
      margin: 0;
      border: 0 solid transparent;
      box-sizing: border-box;
      z-index: 9999;
      width: 100dvw;
      height: 100dvh;
      display: block;
      background-color: transparent;
    }`
    if (hostCss !== this.lastHostCss) {
      this.hostCss?.replaceSync(hostCss)
      this.lastHostCss = hostCss
    }
  }

  connectedCallback() {
    this.bundledCSS = new CSSStyleSheet()
    this.bundledCSS.replaceSync(bundledStyles())

    this.lastHostCss = ''
    this.hostCss = new CSSStyleSheet()
    this.updateHostCss()

    this.shadow.adoptedStyleSheets = [
      this.bundledCSS,
      this.hostCss
    ]

    this.render()
  }

  disconnectedCallback() {
    this.root?.unmount()
    this.root = undefined
    this.shadow.adoptedStyleSheets.length = 0
    this.bundledCSS = undefined
    this.hostCss = undefined
  }

  protected get view(): DiagramView {
    const id = this.getAttribute('view-id') || 'index'
    let view = LikeC4Views[id as LikeC4ViewId]
    if (view) {
      return view
    }

    console.error(`Invalid view id: ${id},\nAvailable: ${Object.keys(LikeC4Views).join(', ')}`)
    view = LikeC4Views['index' as LikeC4ViewId] ?? Object.values(LikeC4Views)[0]
    invariant(view, `Empty LikeC4Views`)
    console.warn(`LikeC4: Falling back to view: ${view.id}`)
    const fallbackViewId = view.id
    setTimeout(() => this.setAttribute('view-id', fallbackViewId), 50)
    return view
  }

  protected render() {
    let view = this.view

    this.updateHostCss()

    this.root ??= createRoot(this.shadow.querySelector('.likec4-react-root')!)

    const colorScheme = matchesColorScheme(this)

    this.root.render(
      <MantineProvider
        theme={theme}
        defaultColorScheme={'auto'}
        {...(colorScheme && { forceColorScheme: colorScheme })}
        getRootElement={() => this.shadowRootEl}
        cssVariablesSelector={'.likec4-shadow-root'}>
        <BrowserModal
          view={view}
          onNavigateTo={(to) => this.setAttribute('view-id', to)}
          onClose={() => this.close()} />
      </MantineProvider>
    )
  }

  close() {
    this.root?.unmount()
    this.root = undefined
    this.parentElement?.removeChild(this)
  }

  attributeChangedCallback(_name: string) {
    if (this.root) {
      this.render()
    }
  }
}
